### ISSUE TITLE
No Admin Panel

### ISSUE THREAD

**Issue by Enzko** [Vateron-Media/Xtream_install#1]
ok

**Comment by Divarion-D** [comment]
it's on port 25500.

**Comment by Enzko** [comment]
│              Preparing Installation              │ 
 └──────────────────────────────────────────────────┘ 
 
chattr: No such file or directory while trying to stat /home/xtreamcodes/iptv_xtream_codes/GeoLite2.mmdb

**Comment by Divarion-D** [comment]
fixed 6ee6745
